### ISSUE TITLE
 Setup_BioMini_SDK_3.10.0.25

### ISSUE THREAD

**Issue by momi133** [sganzerla/finger-biometrics-dotnet#2]
Hi bro
Size of  Setup_BioMini_SDK_3.10.0.25 is 0 Mb.
plz reupload file again.
thanks

**Comment by sganzerla** [comment]
I'm sorry, my space on Google Drive was full. But luckily I had a backup somewhere else. I had no idea it was useful to other people. @momi133 👍

**Comment by sganzerla** [comment]
Hi. Fixed.

Em sex., 16 de ago. de 2024 08:22, momi133 ***@***.***>
escreveu:

**Comment by momi133** [comment]
Thanks a lot bro. It's Solved
